### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Maniues** [AppFlowy-IO/AppFlowy-Cloud#1]
Hello,
this repository has not license.
I saw that LICENSE file was removed in one commit. Why?

**Comment by iswarmondal** [comment]
Hey, I would like to take this issue and add the appropriate licence file. 
Would you guys like to keep the old licencing or go for a new one. I can look into the commits and find the file from there. Let me know 😀

**Comment by annieappflowy** [comment]
It was removed by accident.
We should add back cc: @appflowy

**Comment by annieappflowy** [comment]
Done
