### ISSUE TITLE
[Bug] Error on docker compose build

### ISSUE THREAD

**Issue by vvatelot** [AppFlowy-IO/AppFlowy-Cloud#10]
**Describe the bug**
I try to launch the application using the `docker-compose.yml` file with the command line

```bash
docker compose up -d --build && docker compose logs -f
```

**To Reproduce**
1. Checkout the code
2. Launch the command line
```bash
docker compose up -d --build && docker compose logs -f
```
3. Resulting error:
```
57.20 error: package `time-macros v0.2.11` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.65.0
57.20 Either upgrade to rustc 1.67.0 or newer, or use
57.20 cargo update -p time-macros@0.2.11 --precise ver
57.20 where `ver` is the latest version of `time-macros` supporting rustc 1.65.0
57.20 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.50/src/recipe.rs:176:27
57.20 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
failed to solve: process "/bin/sh -c cargo chef cook --release --recipe-path recipe.json" did not complete successfully: exit code: 101
```

**Expected behavior**
The application is built and ran in docker

**Desktop (please complete the following information):**
 - OS: Linux (ubuntu 22.04)
 - Docker 24.0.5
 - Docker compose v2.20.2

**Additional context**
None

**Comment by kurokawaikki** [comment]
Hi,

I have the same error here.
I already installed and updated the rustc to 1.75. But still stucked at this error...

**Comment by kurokawaikki** [comment]
Hi,
I found the solution.
Please modify the first code in the Dockerfile.
From `FROM lukemathwalker/cargo-chef:latest-rust-1.65.0 as chef` to `FROM lukemathwalker/cargo-chef:latest-rust-1.72.0 as chef` 
Rerun the `sudo docker compose up -d` then it should work now.

**Comment by kurokawaikki** [comment]
Hi,
But I found another error in the app flowy server log.
appflowy_server: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
Any idea to solve it?

**Comment by vvatelot** [comment]
Same here, and unfortunately, no idea to solve this

**Comment by vvatelot** [comment]
Oh yes... Almost :slightly_smiling_face: https://community.fly.io/t/rust-server-missing-libssl-so-3-on-new-deploy/15114/3

I changed to `FROM debian:bookworm-slim AS runtime` but now I have another issue:

```
thread 'main' panicked at 'Failed to connect to Postgres at DatabaseSetting { username: "postgres", password: "password", port: 5432, host: "postgres", database_name: "appflowy", require_ssl: false }.', /app/src/application.rs:113:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: appflowy_server::main::{{closure}}
   3: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
   5: tokio::runtime::scheduler::current_thread::Context::enter
   6: tokio::runtime::context::scoped::Scoped<T>::set
   7: tokio::runtime::context::set_scheduler
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
   9: tokio::runtime::context::runtime::enter_runtime
  10: tokio::runtime::runtime::Runtime::block_on
  11: appflowy_server::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by vvatelot** [comment]
OK, let's make a Pull Request... :wink:

**Comment by speed2exe** [comment]
@vvatelot This should be fix in the main branch. I'll close this, feel free to reopen if you are still having issues
