### ISSUE TITLE
[help] give me a favor

### ISSUE THREAD

**Issue by wx-11** [AppFlowy-IO/AppFlowy-Cloud#1026]
抱歉..我找不到文档才使用issue  希望没有打扰

我不太会编程 从白天到晚上将近10小时 使用搜索引擎 ai 搜索issue后 终于明白了如何部署和解决日志报错, 但是我没有找到关于更新的文档和说明.
但是在[migrations](https://github.com/AppFlowy-IO/AppFlowy-Cloud/tree/main/migrations)我发现了非常多sql文件

我想知道我以后能否在目录 `pull` 然后`up`来更新 还是需要每次执行最新的sql来兼容最新版数据库? 如果是需要sql应该在哪里怎样执行?

希望没有打扰 如果不符合规范 可以关闭issue 谢谢

***
Sorry... I couldn't find documentation, which is why I'm using an issue. I hope I'm not disturbing anyone.

I'm not very experienced with programming. After nearly 10 hours from day to night, I finally understood how to deploy and resolve the log errors, but I couldn't find any documentation or instructions about updates.

However, in [migrations](https://github.com/AppFlowy-IO/AppFlowy-Cloud/tree/main/migrations), I found many SQL files. I would like to know if I can update in the future by just doing a `pull` and then `up` in the directory, or if I need to execute the latest SQL each time to make the database compatible with the newest version? If SQL execution is needed, where and how should I execute the updates?

I hope I'm not causing any disturbance. If this doesn't follow the proper format, feel free to close the issue. Thank you.

**Comment by khorshuheng** [comment]
1. Apart from the migrations under the https://github.com/AppFlowy-IO/AppFlowy-Cloud/tree/main/migrations/before , all the other migrations will be applied when appflowy cloud starts. So there is no need to apply them manually.
2. You can ignore the warning, it's not used if you are using Minio.

**Comment by khorshuheng** [comment]
Yes, that's correct.
