### ISSUE TITLE
[FR] Some incompatible client experiences

### ISSUE THREAD

**Issue by wx-11** [AppFlowy-IO/AppFlowy-Cloud#1027]
<details>
<summary>Original Chinese Text</summary>

创建自己的服务端使用window客户端 发现了以下兼容性问题

1. 登录自己的服务器 但是右上角创建的分享链接依旧是appflowy.com官方域名链接.
![image](https://github.com/user-attachments/assets/f9c82f4a-0b1e-4f4c-9c48-7b74a574ef16)
而且访问不存在 即使我登陆了appflowy.com官方账号 意味着数据并不在官方 而是在自己的服务端
![image](https://github.com/user-attachments/assets/f21c7525-f2c7-458a-b23e-af431cab615a)
可是换成自己的域名 又是404
![image](https://github.com/user-attachments/assets/7046ed18-4759-41e8-93c9-73c2901dd0a7)
那么数据到底在哪?以后能否使用自托管的域名来创建分享和协助链接?

2. 无法使用模板的功能.即使模板会调用客户端 但是数据依然存储在官网账号.
ps: 比如模板市场https://appflowy.io/templates/startups/ed7a9d24-f196-42c1-bbf4-89e1ef965ce0 在网页不登陆appflowy.com将无法看到预览图.而登录appflowy.com后又会储存到appflowy.com网页版账号里.并不会储存到对应客户端的自托管账号里.即使一直唤醒客户端.
我意识到:这个并不是利用scheme传递模板数据,只是单纯打开,储存模板在网页就已经通过api接口储存了 
![image](https://github.com/user-attachments/assets/f6d58b03-61b3-4558-84b3-026cbdfd3f20) 
![image](https://github.com/user-attachments/assets/6407bea8-14b0-43ae-bd1b-7cc3e046ad9c)
f12一看如我所料 同时也能确认只是唤醒客户端 并没有传递
![image](https://github.com/user-attachments/assets/74c004ac-2be9-4cfa-b612-4c3f765ac3d0)
 能否支持通过scheme传递到客户端导入?
3. 我创建了ai容器
![image](https://github.com/user-attachments/assets/9878eced-5311-409d-bea4-09c3c5fbc646)
但是很快我意识到这些好像没有关联:有一些建议:
- 只能填入oai官方key 但是却支持使用claude模型
![image](https://github.com/user-attachments/assets/d2d6d2b5-ff97-4043-99ea-0dffe1c6ace2)
- 使用ai发现没有任何响应结果 我意识到可能是超时了? 我没办法抓包客户端验证这些 如果是超时 很有可能没有走后端接口 而是客户端访问oai了
- 而且由于我所在国家的限制 我无法使用oai官方base_url 我使用[中转api](https://github.com/Calcium-Ion/new-api)希望可以支持自定义base_url.这样即可以支持更多地区也可以支持一个baseurl匹配更多模型
- 客户端期望可以自定义模型 或者扫描base_url的/models接口自动更新 这样开发团队也不需要频繁更新模型列表
所以我建议支持baseurl 比较简单 有一下好处
+ 可以扫描/models接口实时获取支持的模型列表 当然客户端可以修改固定模型列表会更好
+ 一个接口可以聚合访问很多模型不需要频繁修改环境变量改key
+ 可以后端访问内网也可以前端访问接口 更自由人性化
4.  https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy#current-limitations
> Current Limitations
> Bundle ID Conflict
> 
> The AppFlowy App built with AppFlowy Cloud currently shares the same bundle ID as the official AppFlowy App. Consequently, you cannot install both versions on the same device simultaneously. We are working on a solution for this issue.
> 
> Ongoing Development of Stable Branch
> 
> The process of building AppFlowy with AppFlowy Cloud using the stable branch is ongoing. Rapid developments and frequent updates in AppFlowy Cloud mean that new features are constantly being added.
> 
> Collaborative Editing
> 
> Currently, collaborative editing is not yet fully supported in the AppFlowy App when built with AppFlowy Cloud. Although collaborative editing data is synchronized across different devices via the AppFlowy Cloud server, the user interface does not instantly update with these synced changes. To see the latest data, you need to reopen the document or database. This feature is still in development.

我不太懂什么意思 是不是意味着我问题1的原因?

5. 我好像没有找到网页使用的入口 是不是不能像notion一样web端在线编辑?

</details>

***

Creating my own server and using the Windows client, I discovered the following compatibility issues:

1. When logging into my own server, the share links created in the top-right corner still show appflowy.com official domain links.
![image](https://github.com/user-attachments/assets/f9c82f4a-0b1e-4f4c-9c48-7b74a574ef16)
Moreover, these links are inaccessible even when I'm logged into an official appflowy.com account, indicating the data isn't on the official server but on my self-hosted server.
![image](https://github.com/user-attachments/assets/f21c7525-f2c7-458a-b23e-af431cab615a)
However, when changing to my own domain, it shows 404
![image](https://github.com/user-attachments/assets/7046ed18-4759-41e8-93c9-73c2901dd0a7)
### **So where exactly is the data? Will it be possible to use self-hosted domains for creating share and collaboration links in the future?**

2. Cannot use the template functionality. Even though templates call the client, the data is still stored in the official website account.
PS: For example, the template marketplace https://appflowy.io/templates/startups/ed7a9d24-f196-42c1-bbf4-89e1ef965ce0 won't show preview images without logging into appflowy.com. After logging in, it stores to the appflowy.com web version account, not to the corresponding client's self-hosted account, even with the client constantly being awakened.
I realized: This isn't using scheme to transfer template data, it just opens the client. The template is stored on the web as soon as it's saved
![image](https://github.com/user-attachments/assets/f6d58b03-61b3-4558-84b3-026cbdfd3f20)
![image](https://github.com/user-attachments/assets/6407bea8-14b0-43ae-bd1b-7cc3e046ad9c)
Looking at F12, as I suspected, it only awakens the client without data transfer
![image](https://github.com/user-attachments/assets/74c004ac-2be9-4cfa-b612-4c3f765ac3d0)
### **Could client-side importing be supported?**

3. I created an AI container  
![image](https://github.com/user-attachments/assets/9878eced-5311-409d-bea4-09c3c5fbc646)  
But I quickly realized these seem to be unconnected. Here are some suggestions:

- Can only input official OpenAI keys but supports using Claude models
![image](https://github.com/user-attachments/assets/d2d6d2b5-ff97-4043-99ea-0dffe1c6ace2)
- When using AI, I found there were no responses at all. I realized it might be timing out? I can't packet capture the client to verify this. If it is timing out, it's very likely not going through the backend API but rather the client is directly accessing OpenAI
- Due to restrictions in my country, I cannot use the official OpenAI base_url. I use [proxy API](https://github.com/Calcium-Ion/new-api) and hope custom base_url can be supported. This would enable support for more regions and allow one base_url to match multiple models
- For the client, I hope it can support custom models or automatically update by scanning the base_url's /models API. This way the development team wouldn't need to frequently update the model list

### Therefore, I suggest **supporting base_url customization**, which is relatively simple and has the following benefits:
+ Can scan the /models API to get real-time supported model lists. Of course, it would be even better if the client could modify fixed model lists
+ One interface can aggregate access to many models without needing to frequently modify environment variables to change keys
+ Can access internal network through backend or access interface through frontend, providing more freedom and user-friendliness
4. Regarding https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy#current-limitations
> Current Limitations
> Bundle ID Conflict
> 
> The AppFlowy App built with AppFlowy Cloud currently shares the same bundle ID as the official AppFlowy App. Consequently, you cannot install both versions on the same device simultaneously. We are working on a solution for this issue.
> 
> Ongoing Development of Stable Branch
> 
> The process of building AppFlowy with AppFlowy Cloud using the stable branch is ongoing. Rapid developments and frequent updates in AppFlowy Cloud mean that new features are constantly being added.
> 
> Collaborative Editing
> 
> Currently, collaborative editing is not yet fully supported in the AppFlowy App when built with AppFlowy Cloud. Although collaborative editing data is synchronized across different devices via the AppFlowy Cloud server, the user interface does not instantly update with these synced changes. To see the latest data, you need to reopen the document or database. This feature is still in development.

I don't quite understand what this means. Is this related to my first issue?

5. I don't seem to find the web entry point. Does this mean it can't be edited online via web browser like Notion / https://appflowy.com/app ?

**Comment by khorshuheng** [comment]
1. Share link / Publish to web / web editing requires a different service (appflowy web), which is currently not bundled with the docker compose file. See https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/873 .  When you visit appflowy.com, you get redirected to this web service. We will prioritize #873 after adding basic editing functionality to appflowy web.

2. Currently, there's no way for self host user to download the template - these templates are actually stored in the database of the official appflow cloud server. So we will need a way to export these templates.

3. AppFlowy AI is required for two different purposes: generate embedding for the documents so that they can be searched, and AI Chat/Writer. The former depends exclusively on OpenAI at the moment, the latter can be switched to either Claude or OpenAI. That's why, in our official appflowy AI deployment, we actually provide the API keys for both services.

Supporting custom base url is indeed a popular request and several issues have been raised in the past. For example, https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/943 . However, even with a custom base url, at present, AppFlowy AI can only support GPT text embeddings. Similar for chat/writer - AppFlowy AI can only support either Claude or OpenAI models. Llama and Minstral are supported only via the local AI paid plugin  (local in this context means that the request is sent to Llama and Minstral model running on the same machine as AppFlowy desktop app, instead of AppFlowy AI) .

4. The document is outdated, it is not related to the first issue.

5. Refer to 1.

**Comment by khorshuheng** [comment]
> Or perhaps an even simpler approach would be to allow template downloads from the website for local client file import. This might be simpler and more convenient.
> 
If we pick up this feature, this is likely the approach that we are going to take. I can't provide any ETA or guarantee that we will pick this up for now, but if we do, this will be included in the announcement in our discord channel for new releases.

**Comment by khorshuheng** [comment]
It is because the features requested here are covered by other issues already.
