### ISSUE TITLE
[Bug] Unable to send email via SendGrid

### ISSUE THREAD

**Issue by 0x00000oak** [AppFlowy-IO/AppFlowy-Cloud#1033]
Hello, I am unable to send email via SendGrid from the appflowy_cloud container. It works from the gotrue container for the magic links using the same SMTP settings though.

**Describe the bug**
When inviting users to a workspace sending email via SendGrid does not work. The user does not get an email. I get the following error in the logs despite having the domain verified:
`{"timestamp":"2024-11-28T14:44:12.022474Z","level":"ERROR","fields":{"message":"Failed to send workspace invite email: permanent error (550): The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements\n\nCaused by:\n    The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements\n\nStack backtrace:\n   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from\n   1: appflowy_cloud::biz::workspace::ops::invite_workspace_members::{{closure}}::{{closure}}::{{closure}}::{{closure}}\n   2: tokio::runtime::task::raw::poll\n   3: std::sys_common::backtrace::__rust_begin_short_backtrace\n   4: core::ops::function::FnOnce::call_once{{vtable.shim}}\n   5: std::sys::pal::unix::thread::Thread::new::thread_start\n   6: <unknown>\n   7: clone"},"target":"appflowy_cloud::biz::workspace::ops","filename":"src/biz/workspace/ops.rs","line_number":473}`

**To Reproduce**
1. Invite user to workspace

**Expected behavior**
Email should be sent.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
Environment variables for SMTP settings in the .env file
```
GOTRUE_SMTP_HOST=smtp.sendgrid.net
GOTRUE_SMTP_PORT=587
GOTRUE_SMTP_USER=apikey
GOTRUE_SMTP_PASS=my-api-key
GOTRUE_SMTP_ADMIN_EMAIL=appflowy@mydomain.com
GOTRUE_SMTP_SENDER_NAME=AppFlowy
```
```
APPFLOWY_MAILER_SMTP_HOST=smtp.sendgrid.net
APPFLOWY_MAILER_SMTP_PORT=465
APPFLOWY_MAILER_SMTP_USERNAME=apikey
APPFLOWY_MAILER_SMTP_EMAIL=appflowy@mydomain.com
APPFLOWY_MAILER_SMTP_PASSWORD=my-api-key
```

Thank you in advance!

**Comment by khorshuheng** [comment]
Might be due to https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/1049 . Could you update your docker compose file by pulling the latest change from git, and try again?

**Comment by 0x00000oak** [comment]
Thank you! The invite emails are now working correctly.
