### ISSUE TITLE
[Bug] Unable to login via magic link

### ISSUE THREAD

**Issue by vladimiroff** [AppFlowy-IO/AppFlowy-Cloud#1066]
### Bug Description

I'm using a self-hosted instance of AppFlowy-Cloud in docker. For authentication I decided to rely only on email (even though magic links are annoying, I consider them as a lesser evil until there is a way to simply login with email and password).

The link comes, but login fails with an obscure `missing field 'owner_name' at line 1 column 528` (see attached screenshot).

Same happens with the android app. Tried switching between `main` and `0.8.6`.

### How to Reproduce

Login fails with `missing field 'owner_name' at line 1 column 528`.

### Expected Behavior

Magic links should log me in

### Operating System

Linux (Flatpak) and Android

### AppFlowy Version(s)

main and 0.8.6

### Screenshots

![app_flowy](https://github.com/user-attachments/assets/f4ec0f81-7ada-4730-8a5b-e02044c9c309)

### Additional Context

The error is reproducible regardless of whether I try to sign up, login as the administrator or click on an invite link.

**Comment by vladimiroff** [comment]
> As you mentioned switching between 0.8.6 and main, by any chance, are you building your own image based on the source, or running AppFlowy Cloud with cargo and the rest of the dependencies (gotrue, postgres, Redis, nginx etc) via docker compose?

I meant switching between different docker images by setting `{{APPFLOWY_*_VERSION}}`.

>  Can you also observe any error log from either Appflowy cloud or gotrue service, when you get the login error?

Yep, here are the logs from the gotrue container:

```
{"component":"api","level":"info","method":"GET","msg":"request started","path":"/verify","referer":"appflowy-flutter://","remote_addr":"192.168.1.1","time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"auth_event":{"action":"login","actor_id":"f47b8645-2641-4cf3-b4e6-54f74ad2cee0","actor_username":"kiril@example.com","actor_via_sso":false,"log_type":"account"},"component":"api","duration":42635633,"level":"info","method":"GET","msg":"request completed","path":"/verify","referer":"appflowy-flutter://","remote_addr":"192.168.1.1","status":303,"time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"appflowy-flutter://","remote_addr":"192.168.1.1","time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"token","metering":true,"msg":"Login","time":"2024-12-12T07:29:00Z","user_id":"f47b8645-2641-4cf3-b4e6-54f74ad2cee0"}
{"auth_event":{"action":"token_revoked","actor_id":"f47b8645-2641-4cf3-b4e6-54f74ad2cee0","actor_username":"kiril@example.com","actor_via_sso":false,"log_type":"token"},"component":"api","duration":24400925,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"appflowy-flutter://","remote_addr":"192.168.1.1","status":200,"time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"component":"api","level":"info","method":"GET","msg":"request started","path":"/user","referer":"appflowy-flutter://","remote_addr":"192.168.1.1","time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"component":"api","duration":2166721,"level":"info","method":"GET","msg":"request completed","path":"/user","referer":"appflowy-flutter://","remote_addr":"192.168.1.1","status":200,"time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"component":"api","level":"info","method":"GET","msg":"request started","path":"/user","referer":"appflowy-flutter://","remote_addr":"172.19.0.6","time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
{"component":"api","duration":1853175,"level":"info","method":"GET","msg":"request completed","path":"/user","referer":"appflowy-flutter://","remote_addr":"172.19.0.6","status":200,"time":"2024-12-12T07:29:00Z","timestamp":"2024-12-12T07:29:00Z"}
```

**Comment by khorshuheng** [comment]
@vladimiroff What is the client version which you are using?

**Comment by vladimiroff** [comment]
I was using 0.7.7. Just tried again with 0.7.8 and it works now :)

P.S.: I still find the idea of magic links annoying. Especially given that I can set a password via the web admin UI.
