### ISSUE TITLE
[Bug] Invalid oauth scheme handler

### ISSUE THREAD

**Issue by TheGesticulator** [AppFlowy-IO/AppFlowy-Cloud#181]
**Describe the bug**
When self-hosting AppFlowy-Cloud and attempting to authenticate via the custom built app on Windows the screen hangs and doesn't authenticate. If you examine the oauth browser popup in devtools you see an error message like this: "Failed to launch 'appflowy-flutter://#access_token=eyJh....' because the scheme does not have a registered handler.". The issue happens because the custom protocol handler used by Cloud is not the same one registered by the custom app build.

Either AppFlowy-Cloud needs to change the scheme it sends or the custom app needs to register an additional scheme for self-hosted.

**To Reproduce**
1. Install AppFlowy-Cloud
2. Build/install the app for self-hosted
3. Launch the app and attempt to authenticate with your OAuth provider.

To complete the oauth workflow you can manually copy the link and change the scheme to appflowy://... and it will perform as expected.

**Expected behavior**
After authenticating with the selected OAuth provider I expect the browser to close and launch the app.

**Screenshots**
The Custom Protocol registered via the app
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/932650/9fd73a47-d970-45c8-b7d0-3477d8c997d0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome/Firefox/Edge

**Additional context**
Relevant code bits in [AppFlowy-Cloud](https://github.com/search?q=repo%3AAppFlowy-IO%2FAppFlowy-Cloud+appflowy-flutter&type=code)
Relevant reg template in [AppFlowy](https://github.com/AppFlowy-IO/AppFlowy/blob/29a6eab1ce5df193508d577594538c301175a460/frontend/scripts/windows_installer/inno_setup_config.iss#L26)

**Comment by speed2exe** [comment]
@TheGesticulator Have you tried the AppFlowy Client in https://github.com/AppFlowy-IO/AppFlowy-with-AppFlowy-Cloud-Build/releases? I tested yesterday on a Windows 11 (Edge) without issues. Let me know if there are still issues.

**Comment by speed2exe** [comment]
Closing this issue due to age. Feel free to reopen or open another issue if you still have questions.
