### ISSUE TITLE
[Bug] Login failed after deleted user

### ISSUE THREAD

**Issue by ThanatosDi** [AppFlowy-IO/AppFlowy-Cloud#200]
**Describe the bug**
login a user after deleted will get error message `code:RecordNotFound msg: Record not found:Record not exist in db. no rows returned by a query that expected to return at least one row)`

**To Reproduce**
1. clean database
2. login Appflowy desktop with the userA by google  (create userA into database)
3. do somethings(add new documemt...)
4. delete userA at admin dashboard
5. check database, userA data still exist but add a deleted_at value
6. Appflowy desktop logout and re-login again
7. get error message: `code:RecordNotFound msg: Record not found:Record not exist in db. no rows returned by a query that expected to return at least one row)`

**Expected behavior**
Login success and create a new account, it mean unable to obtain previous data

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Appflowy Version: 0.3.9

**Comment by ThanatosDi** [comment]
@speed2exe today I try down container and delete all volumes, then pull all images and up container.
It still can't login after delete the user.

**Comment by speed2exe** [comment]
@ThanatosDi did you git pull to get the latest changes in the repository?

**Comment by ThanatosDi** [comment]
> @ThanatosDi did you git pull to get the latest changes in the repository?
> 
> for a quick fix, you can go to the pgadmin (https://yourhost/pgadmin), delete the record in the `public.af_user` table

Yes, after delete the user record in ad_user table, the user account can login

**Comment by speed2exe** [comment]
@ThanatosDi Thanks for feedback! I'll close this for now. Feel free to reopen or open another issue if you have anymore more questions.
