### ISSUE TITLE
[Bug] build/run_local_server.sh has error on ubuntu 20.04 local server

### ISSUE THREAD

**Issue by nrobin** [AppFlowy-IO/AppFlowy-Cloud#272]
**Describe the bug**
When I run build/run_local_server.sh

**To Reproduce**
1. copy dev.env .env
2. ./build/run_local/server.sh
3. See error
   Compiling realtime-entity v0.1.0 (/home/kyrha/appflowy/AppFlowy-Cloud/libs/realtime-entity)
error: failed to run custom build command for `realtime-entity v0.1.0 (/home/kyrha/appflowy/AppFlowy-Cloud/libs/realtime-entity)`

Caused by:
  process didn't exit successfully: `/home/kyrha/appflowy/AppFlowy-Cloud/target/debug/build/realtime-entity-fbd67079c97c8cdd/build-script-build` (exit status: 1)
  --- stderr
  Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
warning: build failed, waiting for other jobs to finish...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [chromei]
 - Version [main branch]

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by speed2exe** [comment]
@nrobin 
I think you are missing the build tools for protocol buffer. I don't use ubuntu, but you can try installing followings to see if works
```
sudo apt update
sudo apt install protobuf-compiler libprotobuf-dev
```

**Comment by speed2exe** [comment]
closing issue due to age. feel free to reopen if issue persists
