### ISSUE TITLE
[Bug] Credentials are logged

### ISSUE THREAD

**Issue by apollo13** [AppFlowy-IO/AppFlowy-Cloud#367]
> {"timestamp":"2024-03-04T16:14:05.362352Z","level":"INFO","fields":{"message":"Connecting to GoTrue with setting: GoTrueSetting { base_url: \"http://gotrue:9999\", ext_url: \"https://appflowy.XXX\", jwt_secret: Secret([REDACTED alloc::string::String]), admin_email: \"XXX\", admin_password: \"XXX\" }"},"target":"appflowy_cloud::application"}

`admin_password` should not get logged.

**Comment by speed2exe** [comment]
thank you for letting us know

**Comment by apollo13** [comment]
Thanks @speed2exe, the same happens for postgres database credentials.

> {"timestamp":"2024-03-11T09:28:29.657346Z","level":"INFO","fields":{"message":"Connecting to postgres database with setting: DatabaseSetting { pg_conn_opts: PgConnectOptions { host: \"postgres\", port: 5432, socket: None, username: \"postgres\", password: Some(\"XXX\"), database: Some(\"postgres\"), ssl_mode: Prefer, ssl_root_cert: None, ssl_client_cert: None, ssl_client_key: None, statement_cache_capacity: 100, application_name: None, log_settings: LogSettings { statements_level: Debug, slow_statements_level: Warn, slow_statements_duration: 1s }, extra_float_digits: Some(\"2\"), options: None }, require_ssl: false, max_connections: 40, database_name: \"postgres\" }"},"target":"appflowy_cloud::application"}
{"v":0,"name":"appflowy_cloud","msg":"Connecting to postgres database with setting: DatabaseSetting { pg_conn_opts: PgConnectOptions { host: \"postgres\", port: 5432, socket: None, username: \"postgres\", password: Some(\"XXX\"), database: Some(\"postgres\"), ssl_mode: Prefer, ssl_root_cert: None, ssl_client_cert: None, ssl_client_key: None, statement_cache_capacity: 100, application_name: None, log_settings: LogSettings { statements_level: Debug, slow_statements_level: Warn, slow_statements_duration: 1s }, extra_float_digits: Some(\"2\"), options: None }, require_ssl: false, max_connections: 40, database_name: \"postgres\" }","level":30,"hostname":"bda1cc00cd3c","pid":1,"time":"2024-03-11T09:28:29.657426976Z","target":"appflowy_cloud::application","line":363,"file":"src/application.rs"}
