### ISSUE TITLE
What is the default login username and password?

### ISSUE THREAD

**Issue by nekomiya-kasane** [AppFlowy-IO/AppFlowy-Cloud#539]
I'm sorry to open such a useless issue. But I just cannot find how to log in admin panel, it requires an email and a password, but I don't know where is the default one. No matter what I entered, it just redirect back to the login page. 

I followed the steps in https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md to set up my server.

**Comment by speed2exe** [comment]
@nekomiya-kasane 
Hi! you can look for this section in `deploy.env` 
```
# This user will be created when AppFlowy Cloud starts successfully
# You can use this user to login to the admin panel
GOTRUE_ADMIN_EMAIL=admin@example.com
GOTRUE_ADMIN_PASSWORD=password
```

Hope this helps!
