### ISSUE TITLE
[Bug]  APPFLOWY_DATABASE_URL configuration does not take effect

### ISSUE THREAD

**Issue by keven1024** [AppFlowy-IO/AppFlowy-Cloud#550]
**Describe the bug**
AppFlowy-Cloud's `APPFLOWY_DATABASE_URL` configuration doesn't work for non-postgres database names

**To Reproduce**
1. Create an `appflowy` database in postgres and create an `appflowy` user to grant ownership of the `appflowy` database.And this user does not have read/write access to the `postgres` database.
2. Create docker container for AppFlowy-Cloud, env configure `APPFLOWY_DATABASE_URL` = `postgres://appflowy:password@postgres:5432/appflowy`
3. Start the docker container

**Expected behavior**
AppFlowy-Cloud should adhere to the database name configured by env to write to the corresponding database, not to the `postgres `database.

**Screenshots**
docker start logs
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/99848979/32245171-a73f-4ea1-8e71-b6fff8bb7049)
If I grant the `appflowy` account to read and write to the `postgres` database, I can see the database being written to
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/99848979/48008155-d6e6-451a-8006-a4b272275de5)
But that's not the result I want, I want it to write to the `appflowy` database
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/99848979/49db7d73-f92b-45d4-8799-adb068605829)

**Desktop (please complete the following information):**

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by smartyhero** [comment]
Currently you can use the `APPFLOWY_DATABASE_NAME` environment variable to specify the database name

**Comment by speed2exe** [comment]
in the future iterations, we will remove `APPFLOWY_DATABASE_NAME`. To ensure compatibility, set database name in both env var
