### ISSUE TITLE
[Bug] Invite mail doesn't reach the addressee

### ISSUE THREAD

**Issue by DrilealoTatarara** [AppFlowy-IO/AppFlowy-Cloud#554]
**Describe the bug**
Invite mail doesn't reach the addressee when trying to invite a member to the space. I've deployed a self-hosted Appflowy Cloud, and worked correctly. All is configured to be reacheable from the local network. Ir works well when changing cloud method to self-hosted cloud, and modifying the base URL. Problem comes when i try to invite someone. It doesn't return any error, appears the confirmation message that tells that invitation was sent successfully, but when go to check it to the mail, isn't there.
I've been checking the logs of the docker compose, and the output is normal, no errors, just telling that the addressee is already invited (i did several tries). Here is the terminal output:

gotrue-1            | {"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"appflowy-flutter://","remote_addr":"172.18.0.9","time":"2024-05-15T10:13:31Z","timestamp":"2024-05-15T10:13:31Z"}
gotrue-1            | {"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"password","metering":true,"msg":"Login","time":"2024-05-15T10:13:32Z","user_id":"d8fbe7f4-fb83-484f-a8f8-88826e1d19e3"}
gotrue-1            | {"auth_event":{"action":"login","actor_id":"d8fbe7f4-fb83-484f-a8f8-88826e1d19e3","actor_username":"admin@innoapps.com","actor_via_sso":false,"log_type":"account","traits":{"provider":"email"}},"component":"api","duration":182663691,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"appflowy-flutter://","remote_addr":"172.18.0.9","status":200,"time":"2024-05-15T10:13:32Z","timestamp":"2024-05-15T10:13:31Z"}
appflowy_cloud-1    | {"timestamp":"2024-05-15T10:13:32.166063Z","level":"WARN","fields":{"message":"User already invited: carlos@innoapps.es"},"target":"appflowy_cloud::biz::workspace::ops","span":{"user_uuid":"UserUuid(c4c8abb4-9b8b-4397-bceb-4c7d8512ba39)","workspace_id":"Path(dd55f426-a8aa-466b-bd31-19c8d6142c1f)","name":"post_workspace_invite_handler"},"spans":[{"client_version":"0.5.7","device_id":"{639EC6A9-BA05-496E-9391-E78269EBBD03}","method":"POST","path":"/api/workspace/{workspace_id}/invite","payload_size":48,"request_id":"82b9c0050af197aa3037b3a512ebdffc","name":"request"},{"user_uuid":"UserUuid(c4c8abb4-9b8b-4397-bceb-4c7d8512ba39)","workspace_id":"Path(dd55f426-a8aa-466b-bd31-19c8d6142c1f)","name":"post_workspace_invite_handler"}]}
nginx-1             | 172.25.220.78 - - [15/May/2024:10:13:32 +0000] "POST /api/workspace/dd55f426-a8aa-466b-bd31-19c8d6142c1f/invite HTTP/1.1" 200 56 "-" "-"

**Comment by speed2exe** [comment]
@DrilealoTatarara currently email sending in upon the first invitation. you can get errors from appflowy_cloud service for invitation email. even if email is not sent, the server keeps a record of email invitations, so the person who is invited is able to login in to admin page, under invite section, accepts the invitation

**Comment by leoniebe** [comment]
I have a similar issue when inviting someone to my workspace i get a failed invite from the local appfloey and when i try it in the admin panel i get the following error: 
![Screenshot_20240716_234009_ChatGPT](https://github.com/user-attachments/assets/85d15538-4999-4e48-9bd5-e15d22932399)

I have the correct credentials for auth using google and also for github

**Comment by speed2exe** [comment]
@leoniebe 
you probably changed the admin password (different from .env).
also, you dont actually need the email to be sent, you can just log in with the invitee's email, then under the invite section, you will see the invite

**Comment by speed2exe** [comment]
@leoniebe I'll close this issue for now. Feel free to reopen if required
