### ISSUE TITLE
[Bug] can not send invite to users

### ISSUE THREAD

**Issue by mickey3721** [AppFlowy-IO/AppFlowy-Cloud#563]
**Describe the bug**
can not send invite to users after pulling the lastest

**To Reproduce**
1. Go to login web page
2. Click on login 
3. go to invite, and sent invite to user

**Expected behavior**
fix the problem

**Screenshots**
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/60539185/d282584a-af30-4f84-b3a7-2cbce4704b49)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: Edge
 - Version: latest
 
**Additional context**
 - Environment: docker in windows wsl unbuntu

**Comment by speed2exe** [comment]
@mickey3721 are you self hosting?

**Comment by mickey3721** [comment]
yes self hosting by windows 11 wsl unbuntu

**Comment by speed2exe** [comment]
@mickey3721 seems like you have changed the admin password which is different from your `.env`, try adjusting it back to see if it works. for now we need to meet the password consistent(might be fixed in the future). workaround is to have another account having admin privileges aside from the admin user. you can check the postgres database in `auth.users` table, look for admin user and copy the role to the user record

**Comment by mickey3721** [comment]
Yes，when I change the admin user password back to default，it can invite others again. Thanks！
Is that means only can change admin password in .env？If I want to change admin password how to do？

发自我的 iPhone

在 2024年5月20日，09:52，Zack ***@***.***> 写道：

﻿

@mickey3721<https://github.com/mickey3721> seems like you have changed the admin password which is different from your .env, try adjusting it back to see if it works. for now we need to meet the password consistent(might be fixed in the future). workaround is to have another account having admin privileges aside from the admin user. you can check the postgres database in auth.users table, look for admin user and copy the role to the user record

**Comment by speed2exe** [comment]
@mickey3721 you can create another user and assign as admin role.

to do so: check the postgres database `auth.users` table, look for the admin user and copy the role column to the target user record
