### ISSUE TITLE
[Bug] can't login after redeploy latest version

### ISSUE THREAD

**Issue by mickey3721** [AppFlowy-IO/AppFlowy-Cloud#609]
**Describe the bug**
after redeploy the latest AppFlowy-Cloud by docker compose, can not login as before
deploy steps:

1.pull all files from repository
2.copy and modified deploy.env to .env
3.docker compose up

**To Reproduce**

**Expected behavior**
How to solve the login problem?

**Screenshots**
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/60539185/15887ef2-084a-45c3-9d02-9619eb95cc9e)

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser [windows edge]
 - Version [latest]

**Additional context**
 - Environment [docker compose, selfhost, linux mint]

**Comment by speed2exe** [comment]
@mickey3721 seems like nginx service not able to find the service. have you tried to restart nginx?

**Comment by mickey3721** [comment]
I already try to restart all containers, even reboot my machine, but nothing change,

Attaching my log and .env file, and container list, pls help me to solve the problem, thks!

![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/60539185/7556c4e3-b6be-4845-8c8a-8bc6a234c909)
[env.txt](https://github.com/user-attachments/files/15783146/env.txt)
[log.txt](https://github.com/user-attachments/files/15783147/log.txt)

**Comment by speed2exe** [comment]
@mickey3721 can you check the `gotrue` service?

```
$ cat ~/Downloads/log.txt | rg gotrue
Attaching to admin_frontend-1, ai-1, appflowy_cloud-1, appflowy_history-1, appflowy_indexer-1, gotrue-1, minio-1, nginx-1, postgres-1, redis-1
admin_frontend-1    | {"timestamp":"2024-06-11T05:51:05.353769Z","level":"INFO","fields":{"message":"config loaded: Config { redis_url: \"redis://redis:6379\", gotrue_url: \"http://gotrue:9999\", appflowy_cloud_url: \"http://appflowy_cloud:8000\", appflowy_cloud_gateway_url: \"http://localhost:8100\" }"},"target":"admin_frontend"}
admin_frontend-1    | {"timestamp":"2024-06-11T05:51:05.392162Z","level":"ERROR","fields":{"error":"calling http://gotrue:9999/health failed"},"target":"gotrue::api","span":{"name":"health"},"spans":[{"name":"health"}]}
``

health check failed

**Comment by mickey3721** [comment]
yes that's some problem with goture.
When I rebuild the gotrue by docker compose, it stuck in configuring postgresql, any key press invaild,
show message below, more detail in attachment log.txt:

#5 719.0 Configuring postgresql-common
#5 719.0 -----------------------------
#5 719.0 
#5 719.0 createcluster.conf: A new version (/tmp/postgresql-common.0IPfrZ) of
#5 719.0 configuration file /etc/postgresql-common/createcluster.conf is available, but
#5 719.0 the version installed currently has been locally modified.
#5 719.0 
#5 719.0   1. install the package maintainer's version
#5 719.0   2. keep the local version currently installed
#5 719.0   3. show the differences between the versions
#5 719.0   4. show a side-by-side difference between the versions
#5 719.0   5. start a new shell to examine the situation
#5 719.0 What do you want to do about modified configuration file createcluster.conf?

**Comment by speed2exe** [comment]
@mickey3721 i have not met with this issue before. perhaps you upgraded your postgresql too? this message shows up as it run, right? perhaps try `docker exec -it <gotrue container>` to see if you can input any option

**Comment by mickey3721** [comment]
I have no idea about it, for building the gotrue make me cracy 
can use the earlier version docker compose file to deploy the server? (using gotrue image instead of building it)

**Comment by speed2exe** [comment]
you should be able to do that
