### ISSUE TITLE
[Bug] Can't invite user to Workspace

### ISSUE THREAD

**Issue by Hope-IT-Works** [AppFlowy-IO/AppFlowy-Cloud#611]
### Describe the bug
When I'm trying to invite a user to my workspace, the user will not get invited and I get an error.

### To Reproduce
1. Go to Web-Panel
2. Login with Discord
4. Click on "**Invite**" in the left side bar
5. In the "**Invite another user to your workspace**" section enter email address
6. Click on the "**Invite**" button on the right

### Expected behavior
The user should get invited.

### Screenshots
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/52013820/e6e69235-6976-44c3-9da5-1940b96a71b3)
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/52013820/8fafd9f9-dbfd-40bd-8364-f77f544be4b0)

**Comment by speed2exe** [comment]
@Hope-IT-Works Hi, are you self-hosting?

**Comment by Hope-IT-Works** [comment]
Yes

**Comment by annieappflowy** [comment]
@Hope-IT-Works , did you manage to make it work? You're welcome to join our [Discord server](https://discord.gg/appflowy-903549834160635914) for quick help.
