### ISSUE TITLE
[Bug] login  error with Google OAuth2

### ISSUE THREAD

**Issue by jkcn18** [AppFlowy-IO/AppFlowy-Cloud#664]
I logged in with Google OAuth2 and confirmed that an error occurred after the Goole account was redirected
<img width="946" alt="error" src="https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/53561678/276cfa07-e292-4edc-b783-50c61a856337">

**Comment by khorshuheng** [comment]
Has these env configuration been configured?
GOTRUE_EXTERNAL_GOOGLE_ENABLED=true
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=
GOTRUE_EXTERNAL_GOOGLE_SECRET=
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://your-host/gotrue/callback

**Comment by jkcn18** [comment]
> Has these env configuration been configured? GOTRUE_EXTERNAL_GOOGLE_ENABLED=true GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID= GOTRUE_EXTERNAL_GOOGLE_SECRET= GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://your-host/gotrue/callback


Yes
<img width="530" alt="error1" src="https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/53561678/ffacf822-1e91-47bb-9e1d-510617782021">

**Comment by khorshuheng** [comment]
Noted. Do you see any error logs from the admin_frontend or gotrue container when this error was shown on the web page?

**Comment by jkcn18** [comment]
> Noted. Do you see any error logs from the admin_frontend or gotrue container when this error was shown on the web page?

I see some message from gotrue，but i dont't know it's mean

{"component":"api","level":"info","method":"GET","msg":"request started","path":"/callback","referer":"appflowy-flutter://","remote_addr":"172.18.0.8","time":"2024-07-10T06:39:40Z","timestamp":"2024-07-10T06:39:40Z"}
{"auth_event":{"action":"login","actor_id":"e8b2c553-a1c9-44c9-a326-827a2751e3b8","actor_name":"xbinji","actor_username":"xbinji@gmail.com","actor_via_sso":false,"log_type":"account","traits":{"provider":"google"}},"component":"api","duration":83166624,"level":"info","method":"GET","msg":"request completed","path":"/callback","referer":"appflowy-flutter://","remote_addr":"172.18.0.8","status":302,"time":"2024-07-10T06:39:40Z","timestamp":"2024-07-10T06:39:40Z"}
{"component":"api","level":"info","method":"GET","msg":"request started","path":"/settings","referer":"appflowy-flutter://","remote_addr":"172.18.0.10","time":"2024-07-10T06:39:40Z","timestamp":"2024-07-10T06:39:40Z"}
{"component":"api","duration":19328,"level":"info","method":"GET","msg":"request completed","path":"/settings","referer":"appflowy-flutter://","remote_addr":"172.18.0.10","status":200,"time":"2024-07-10T06:39:40Z","timestamp":"2024-07-10T06:39:40Z"}
{"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"appflowy-flutter://","remote_addr":"172.18.0.10","time":"2024-07-10T06:39:41Z","timestamp":"2024-07-10T06:39:41Z"}
{"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"token","metering":true,"msg":"Login","time":"2024-07-10T06:39:41Z","user_id":"e8b2c553-a1c9-44c9-a326-827a2751e3b8"}
{"auth_event":{"action":"token_revoked","actor_id":"e8b2c553-a1c9-44c9-a326-827a2751e3b8","actor_name":"xbinji","actor_username":"xbinji@gmail.com","actor_via_sso":false,"log_type":"token"},"component":"api","duration":8023495,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"appflowy-flutter://","remote_addr":"172.18.0.10","status":200,"time":"2024-07-10T06:39:41Z","timestamp":"2024-07-10T06:39:41Z"}
{"component":"api","level":"info","method":"POST","msg":"request started","path":"/token","referer":"appflowy-flutter://","remote_addr":"172.18.0.10","time":"2024-07-10T06:39:41Z","timestamp":"2024-07-10T06:39:41Z"}
{"action":"login","instance_id":"00000000-0000-0000-0000-000000000000","level":"info","login_method":"token","metering":true,"msg":"Login","time":"2024-07-10T06:39:41Z","user_id":"e8b2c553-a1c9-44c9-a326-827a2751e3b8"}
{"auth_event":{"action":"token_revoked","actor_id":"e8b2c553-a1c9-44c9-a326-827a2751e3b8","actor_name":"xbinji","actor_username":"xbinji@gmail.com","actor_via_sso":false,"log_type":"token"},"component":"api","duration":8633035,"level":"info","method":"POST","msg":"request completed","path":"/token","referer":"appflowy-flutter://","remote_addr":"172.18.0.10","status":200,"time":"2024-07-10T06:39:41Z","timestamp":"2024-07-10T06:39:41Z"}

**Comment by speed2exe** [comment]
@jkcn18 do you have logs to `admin_frontend` service, or the full error message(the screenshot seems truncated)? Using browser inspect tools (usually right click -> inspect -> network) may also help to find the root cause. from what it seems, your are successfully authenticated, but token is not stored properly in redis.

**Comment by annieappflowy** [comment]
No response for a few months. Closing it
