### ISSUE TITLE
[Bug] AI Server DNS can't be resolved

### ISSUE THREAD

**Issue by suntorytimed** [AppFlowy-IO/AppFlowy-Cloud#676]
**Describe the bug**
After 0.6.2 of AppFlowy resolved the issue of stuck AI requests I am now at the stage I can test the AI server of AppFlowy Cloud. When doing an AI request in AppFlowy I receive following error:

```
{"code":1017,"message":"Invalid request:reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"ai\")), port: Some(5001), path: \"/completion/stream\", query: None, fragment: None }, source: Error { kind: Connect, source: Some(ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: Name or service not known\" })) } }"} 
```

**To Reproduce**
1. Deploy AppFlowy-Cloud with the default docker-compose.yml and deploy.env but adding your own passwords
2. Keep `APPFLOWY_AI_SERVER_HOST=ai` and `APPFLOWY_AI_SERVER_PORT=5001`
3. Do an AI request with a logged in user in AppFlowy 0.6.2

**Expected behavior**
The request is successfully handled by OpenAI

**Screenshots**
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/2744377/acebe371-a9a7-4507-9028-a86ad64b0242)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser n. a.
 - Version 0.5.28 of Server and 0.6.2 of AppFlowy client

**Additional context**
-

**Comment by khorshuheng** [comment]
Just to check: is the AI service running? In addition, is APPFLOWY_AI_OPENAI_API_KEY set?

**Comment by suntorytimed** [comment]
Lastest `git pull` and `docker-compose pull` fixed all my issues. I suspect an issue with the last rebase I had to do to fix the `deploy.env`.
