### ISSUE TITLE
[Bug] Invalid Grant error when trying to invite user to the workspace

### ISSUE THREAD

**Issue by patrykbojczuk** [AppFlowy-IO/AppFlowy-Cloud#688]
**Describe the bug**
When trying to invite a user to the workspace by the owner (and supabase_admin), the self-hosted cloud responds with the auth-related Internal Server Error and user is not invited.
The `OAuthError` returned in the response is `invalid_grant` - Invalid login credentials.

**To Reproduce**
1. Go to the Web Panel
2. Click on the "Invite" link on the sidebar
3. In the "Invite another user to your workspace" section, in the input field in the "Invite" column enter the email address
4. Click on the "Invite" button next to the input field
4. See the error (fig. 1.)

Alternatively in the desktop app:
1. Go to the Settings
2. Click on the "Members" tab on the sidebar
3. In the "Invite members" section, in the "invite by email" field enter the email address
4. Click on the "Send invite" button next to the input field
5. See the error (fig. 2.)

**Expected behavior**
When clicking on the "Invite"/"Send invite" button, user gets invited and no error is thrown.

**Screenshots**
![image](https://github.com/user-attachments/assets/96d8bac5-d93d-4991-b6ad-ee28a899ad52)
Fig. 1. Web App

![image](https://github.com/user-attachments/assets/e568b138-aa44-4e8c-9657-f3107df3f67c)
Fig. 2. Desktop App

**Desktop:**
 - OS: macOS
 - Browser: Brave
 - Version: v1.67.123, Chromium: 126.0.6478.126
 - Cloud is hosted on Ubuntu 24.04.

**Additional context**
GoTrue logs
```json
{
    "component": "api",
    "level": "info",
    "method": "POST",
    "msg": "request started",
    "path": "/token",
    "referer": "appflowy-flutter://",
    "remote_addr": "172.24.0.8",
    "time": "2024-07-14T08:04:46Z",
    "timestamp": "2024-07-14T08:04:46Z"
}
```
```json
{
    "component": "api",
    "error": "invalid_grant: Invalid login credentials",
    "level": "info",
    "method": "POST",
    "msg": "invalid_grant: Invalid login credentials",
    "path": "/token",
    "referer": "appflowy-flutter://",
    "remote_addr": "172.24.0.8",
    "time": "2024-07-14T08:04:46Z",
    "timestamp": "2024-07-14T08:04:46Z"
}
```
```json
{
    "component": "api",
    "duration": 71181028,
    "level": "info",
    "method": "POST",
    "msg": "request completed",
    "path": "/token",
    "referer": "appflowy-flutter://",
    "remote_addr": "172.24.0.8",
    "status": 400,
    "time": "2024-07-14T08:04:46Z",
    "timestamp": "2024-07-14T08:04:46Z"
}
```
 
Cloud logs
```json
{
    "timestamp": "2024-07-14T08:04:46.130005Z",
    "level": "ERROR",
    "fields": {
        "error": "error: invalid_grant, description: Some(\"Invalid login credentials\")"
    },
    "target": "appflowy_cloud::api::workspace",
    "span": {
        "user_uuid": "UserUuid(ea47898b-da0e-4fd4-ac00-4eeecd3a0e93)",
        "workspace_id": "Path(d4943d06-37cb-4afd-ad48-d16880ea3ae5)",
        "name": "post_workspace_invite_handler"
    },
    "spans": [
        {
            "method": "POST",
            "path": "/api/workspace/{workspace_id}/invite",
            "payload_size": 50,
            "request_id": "c0ce8f33-76a4-46ca-b070-11da80a91131",
            "name": "request"
        },
        {
            "user_uuid": "UserUuid(ea47898b-da0e-4fd4-ac00-4eeecd3a0e93)",
            "workspace_id": "Path(d4943d06-37cb-4afd-ad48-d16880ea3ae5)",
            "name": "post_workspace_invite_handler"
        }
    ]
}
```

This bug is possibly related to #611.

**Comment by speed2exe** [comment]
@patrykbojczuk you possibly have changed the admin or password after login? It should only be changed in the `.env` config file

**Comment by patrykbojczuk** [comment]
@speed2exe That's weird design, but yeah, that's has to be it. Thanks!
