### ISSUE TITLE
[Bug] Unable to complete email authentication

### ISSUE THREAD

**Issue by PacteraZhangTong** [AppFlowy-IO/AppFlowy-Cloud#729]
When I log in using Mail.
I received the authentication email, click on Log In to jump to the following page
The URL is http://myhost/verify?token=...
I need to manually change the URL to http://myhost/gotrue/verify?token=... To open Appflowy normally
How to solve this problem? 

![image](https://github.com/user-attachments/assets/139999ca-296a-46c5-bac7-5af89272f215)

 - OS: Ubuntu 24.04 LTS
 - Browser chrome

**Comment by speed2exe** [comment]
@PacteraZhangTong can you check that the environment `GOTRUE_MAILER_URLPATHS_*` in your `docker-compose.yml` file? It should be `/gotrue/verify`

**Comment by PacteraZhangTong** [comment]
> @PacteraZhangTong can you check that the environment `GOTRUE_MAILER_URLPATHS_*` in your `docker-compose.yml` file? It should be `/gotrue/verify`

Thank you for your reply
I am using the `docker-compose-dev.yml` file, so I checked my `docker-compose-dev.yml` only found `GOTRUE_MAILER_URLPATHS_CONFIRMATION=/verify`. After modifying it to '/gothue/verify', the problem was not resolved.
Then I found the `docker-compose. yml` file and found the following code
```
GOTRUE_MAILER_URLPATHS_INVITE=/gotrue/verify
GOTRUE_MAILER_URLPATHS_RECOVERY=/gotrue/verify
GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/gotrue/verify
```
Adding this code to the `docker-compose-dev.yml` file solved the problem.
