### ISSUE TITLE
[Bug] Problems with postgres and nginx

### ISSUE THREAD

**Issue by CrackAndDie** [AppFlowy-IO/AppFlowy-Cloud#758]
I have a server with an ASP.NET Api running with docker compose. It uses the ports 443, 80. There is also a postgres already installed on my server on port 5432. I've changed the port of yours postgres to 5433 and as I understood it works fine now (not sure). But there is still a problem with nginx because the ports are already used by api (screenshort below shows you the problem when I do ```docker compose up```) :

```
[+] Running 11/12
 ✔ Network appflowy-cloud_default               Created                                                       0.1s 
 ✔ Volume "appflowy-cloud_postgres_data"        Created                                                       0.0s 
 ✔ Volume "appflowy-cloud_minio_data"           Created                                                       0.0s 
 ✔ Container appflowy-cloud-admin_frontend-1    Started                                                       2.0s 
 ✔ Container appflowy-cloud-ai-1                Started                                                       1.9s 
 ⠋ Container appflowy-cloud-nginx-1             Starting                                                      2.0s 
 ✔ Container appflowy-cloud-postgres-1          Started                                                       1.7s 
 ✔ Container appflowy-cloud-redis-1             Started                                                       1.7s 
 ✔ Container appflowy-cloud-gotrue-1            Started                                                       1.6s 
 ✔ Container appflowy-cloud-minio-1             Started                                                       1.8s 
 ✔ Container appflowy-cloud-appflowy_cloud-1    Started                                                       1.9s 
 ✔ Container appflowy-cloud-appflowy_history-1  Started                                                       1.8s 
Error response from daemon: driver failed programming external connectivity on endpoint appflowy-cloud-nginx-1 (e1dd0f296d45b9254ddbe230f1eda95e82b766ef83ac168f0c0c4e810f686f9b): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
```

**To Reproduce**
1. Have a server with a nginx installed and configured ports 443, 80 to another docker containers.
2. Try to ```docker compose up``` AppFlowy

**Expected behavior**
I expected it to run on a custom port (I do not want to care about managing ports for postgres and other) so I could just specify the port in AppFlowy application. Docker was created so the end-point user won't have such a headache. But! I still appreciate Your work because I understand how much effort does it take.  

So I hope there a way of configuring AppFlowy nginx so it won't collapse with mine on my server

**Screenshots**

--

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser -
 - Version: latest clone of the repo

**Additional context**

--

**Comment by khorshuheng** [comment]
You can modify the nginx port mapping here:    https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/5badffc97b17984d5f25a178c0c5a477338039c4/docker-compose.yml#L9

**Comment by CrackAndDie** [comment]
Won't it break anything? Is there any web callbacks in the code that are hardcoded to the 80 port?

**Comment by khorshuheng** [comment]
You will need to modify the API_EXTERNAL_URL and the gotrue callback URL in the env file as well, depending on your hostname and the port that you are running the nginx on.
