### ISSUE TITLE
[Bug] Unable to retrieve uploaded file

### ISSUE THREAD

**Issue by Adolar13** [AppFlowy-IO/AppFlowy-Cloud#818]
**Describe the bug**
When uploading a file (e.g. .txt) to appflowy using a self-hosted cloud, the file gets uploaded sucessfully, but clicking on the file fails to retrieve it again, giving the following http response:
`{
    "code": 1017,
    "message": "Can't find the user uuid from the request: No Authorization header"
}`

**To Reproduce**
1. Self-host appflowy cloud
2. Connect to your instance
3. upload a file (e.g. .txt) to a document
4. Click on the file
5. See error in browser

**Expected behavior**
The file should be retrieved when clicking on it.

**Desktop (please complete the following information):**
 - OS: iOS, macOS
 - Browser: Chrome, Safari
 - Version: cloud 0.6.18, appflowy 0.6.9

**Additional context**
 - self-hosted on mac m2 using docker compose

**Comment by Tafeen** [comment]
I'm getting the same error with cloud version: 0.6.10 and desktop version: 0.6.8

**Comment by ltkermit** [comment]
I am also getting this error.

- Desktop Version (Windows 11): 0.6.9
- Android Version: 0.6.9
- Cloud Version: 0.6.18

Self hosting with Proxmox CT using Ubuntu 24.04

**Comment by rdmax** [comment]
same error

**Comment by speed2exe** [comment]
For a temporary fix, you may try setting the `APPFLOWY_ACCESS_CONTROL=false` in the `.env` and see if it works.

**Comment by ltkermit** [comment]
> For a temporary fix, you may try setting the `APPFLOWY_ACCESS_CONTROL=false` in the `.env` and see if it works.

I just tried that and it did work for me. Thank you for that tip.

**Comment by casainho** [comment]
Same issue with me :-(
