### ISSUE TITLE
[FR] Self-hosted docker image Feature Request

### ISSUE THREAD

**Issue by joebnb** [AppFlowy-IO/AppFlowy-Cloud#825]
would appflowy creata a automation for auto publish  Appfloy-cloud docker image instead of self build in git repo

and make it can configurated custom db、minio、nginx、redis service url，this may use shared service.

**Comment by DenuxPlays** [comment]
I already opened an issue: https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/791

There are already docker images and you just have to copy 2 more files.

**Comment by khorshuheng** [comment]
Closed as this is being tracked in #791 .
