### ISSUE TITLE
[Bug] Unable to send emails

### ISSUE THREAD

**Issue by DenuxPlays** [AppFlowy-IO/AppFlowy-Cloud#827]
**Describe the bug**

Whenever my application tries to send an email it does not work.
The credentials are correct (as when I try to send a mail from nextcloud with the same credentials it works).

**To Reproduce**
1. Deploy the cloud
2. Enter your smtp credentials (or use mailhog for testing)
3. Try to send an email

**Expected behavior**

Sends the email without an error.

**Screenshots**

No screenshot but error log:
1. 
```json
{
  "auth_event": {
    "action": "user_recovery_requested",
    "actor_id": "31b6bfab-b324-4829-9ad9-00a672bf4ab2",
    "actor_username": "***",
    "actor_via_sso": false,
    "log_type": "user"
  },
  "component": "api",
  "error": "Error sending magic link email: 535 Authentication failed: Bad username / password",
  "level": "error",
  "method": "POST",
  "msg": "500: Error sending magic link",
  "path": "/magiclink",
  "referer": "/",
  "remote_addr": "172.18.0.11",
  "request_id": "df85f6e0-9c73-4eef-b3bc-2951129a4a53",
  "time": "2024-09-16T11:03:30Z"
}
```
```json
{
  "auth_event": {
    "action": "user_recovery_requested",
    "actor_id": "31b6bfab-b324-4829-9ad9-00a672bf4ab2",
    "actor_username": "***",
    "actor_via_sso": false,
    "log_type": "user"
  },
  "component": "api",
  "duration": 296024987,
  "level": "info",
  "method": "POST",
  "msg": "request completed",
  "path": "/magiclink",
  "referer": "/",
  "remote_addr": "172.18.0.11",
  "request_id": "df85f6e0-9c73-4eef-b3bc-2951129a4a53",
  "status": 500,
  "time": "2024-09-16T11:03:30Z"
}
```

**Desktop (please complete the following information):**
 - OS: Fedora 40
- latest tag (atm 0.6.21)

**Additional context**

///

**Comment by DenuxPlays** [comment]
Note:
This make the app unusable as you cannot login with a password.

**Comment by matart15** [comment]
this is current app login window

![Screenshot 2025-01-06 at 14 01 28](https://github.com/user-attachments/assets/899d3324-0a6f-45e9-9b9f-06cd7fb7eb0b)

if i set selfhosted url and try to login ti gives above error.

## BUT

When i login to admin dashboard and click `open AppFlowy` it opened app in login state.

![Screenshot 2025-01-06 at 14 06 11](https://github.com/user-attachments/assets/08908305-6b28-4ba7-8fa1-14008f1e8699)

Is it intended use or just work around?

either way
1. selfhost AppFlowy-cloud
2. download AppFlowy-App
3. setup own url for AppFlowy-App
4. login with AppFlowy-App

this should be normal way and it should work. with or without password. ( most people think it is the flow )

**Comment by matart15** [comment]
I also wondering How non admin users login to my self hosted instance?

**Comment by khorshuheng** [comment]
I have updated the FAQ to address this: https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md#can-i-sign-in-using-only-using-email-and-password

Usually, users will login to AppFlowy via one of the identity providers (Google, Apple, Discord, Github), or magic link (requires SMTP to be setup). When you provide your email as an input in the AppFlowy app, and click login, a link will be sent to the email, and you can login to AppFlowy via the link. Once logged in, the access token will be valid for some time, so you don't have to go through this process again, until the token expires.

There are users who don't want to use any of the identify providers, nor do they want to use magic link. In which case, they can use the admin frontend portal to login. After you login using the admin credential, on the top left corner, you can create an user with password. This credential can then be used to login to the admin frontend portal, and open AppFlowy app.
