### ISSUE TITLE
[Bug] Extra Spacing Added to AI Writer Response

### ISSUE THREAD

**Issue by StreamlinedStartup** [AppFlowy-IO/AppFlowy-Cloud#845]
**Describe the bug**
When using the AI writer, it introduces a bunch of seemingly random spaces after words and punctuation. 

**To Reproduce**

1. Use the AI Writer and wait for response

**Expected behavior**
A clean response from OpenAI. 

**Screenshots**
https://github.com/user-attachments/assets/793a42d2-3235-4118-8207-3a85bf07290e

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5 (23F79), Apple Silicon
 - Browser - n/a
 - Version - AppFlowy App 0.6.9 (0.6.9)

**Additional context**
- Docker selfhosted: latest (9/27/24)

**Comment by annieappflowy** [comment]
This issue was fixed 
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/cbbcea68-f7ed-40e8-b184-b8112d36228e" />
