### ISSUE TITLE
[FR] Remove/Document implicit assumptions on postgres roles and priviledge

### ISSUE THREAD

**Issue by khorshuheng** [AppFlowy-IO/AppFlowy-Cloud#861]
Currently, there are some implicit assumptions being made on the postgres roles and priviledge that are not well documented:

1. It is assumed that the user will run the following migration script on database start: https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/9c0dffacef6b58070002d988fffd92d09e5516a8/docker-compose.yml#L36 . This migration script assumes that the postgres user executing the script has the priviledge of creating roles.
2. `anon`, `supabase_auth_admin` and `authenticated` postgres user/role are assumed to exists. which are supposed to be created by the script above. However, the `anon` and `authenticated` requirement are likely due to dependency on supabase in the past, which is no longer the case. If possible, the dependencies to these roles should be removed.
3. Without `anon` and `authenticated` roles, the following migrations will fail:
- 20230312043023_user.sql
- 20230906101222_workspace.sql
- 20230906102651_collab.sql
4. It is also assumed that the database name is "postgres", due to: https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/9c0dffacef6b58070002d988fffd92d09e5516a8/migrations/before/20230312043000_supabase_auth.sql#L35C22-L35C58  .
5. The postgres user used by gotrue service is assumed to be supabase_auth_admin and the password is hard coded to root (https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/9c0dffacef6b58070002d988fffd92d09e5516a8/migrations/before/20230312043000_supabase_auth.sql#L29) Using a different database url can result in gotrue service start up error due to lack of access to auth schema / not able to find the auth schema.
6. It is assumed that both gotrue and appflowy cloud service shares the same database, and the default search path for supabase_auth_admin is the auth schema. Otherwise, appflowy cloud will fail during start up, due to: https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/9c0dffacef6b58070002d988fffd92d09e5516a8/src/application.rs#L409
7. The database user for AppFlowy Cloud must be able to access and modify the tables in the auth schema. Several migrations in AppFlowy Cloud modifies the tables in auth schema.
8. The before_migration script didn't grant appflowy cloud's database user the above priviledge. The docker compose setup will only work if the database user happens to be a superuser eg. postgres.
9. Likewise, it is also assumed that the appflowy database user can create postgres extension eg. pgvector. This is not possible unless the user is superuser.

**Comment by Schoumi** [comment]
You've summarize the problem I encounter/have encounter trying to run AppFlowy Cloud outside of docker.
The fact that the user is not a superuser make that all migration with **public** schema in it fails since they are created with **auth** schema. You have to change any mention of postgres/supabase_auth_admin in these scripts,...
20231130150000_user_id_foreign_key.sql REVOKE Rights granted in a previous migration that doesn't affect postgres superuser but affect any other user

I don't know how your ORM work and if it's possible. In Android SQLite Core Library exist a version number that correspond to the version of physical data model of the database. Dev has to make two function: onCreate and onUpgrade.
- onCreate create the schema for the last version of the physical data model if it's the first installation of the app. New user doesn't have to go througt any migrations. This functions is execute one and only one time.
- onUpgrade has the old database version and the new database version. It allow devs to make migrations for user that already have the app installed before and have to run some migrations.

I love this approach because new installation has the latest and cleanest version out of the box without any migration. Devs can read the onCreate function to know what is the physical data model  and it work the same if you use Room has ORM (Entity Driven). 

Anyway this is all the script i have to modify (supabase_auth_admin/public/postgres/rights management problems):
```
	modified :         migrations/20230312043023_user.sql
	modified :         migrations/20231130140000_user_delete_trigger.sql
	modified :         migrations/20231130150000_user_id_foreign_key.sql
	modified :         migrations/20240123140707_workspace_owner_trigger.sql
	modified :         migrations/20240304173938_workspace_invitation.sql
	modified :         migrations/20240306110000_workspace_invitation_2.sql
	modified :         migrations/20240626184736_publish_collab_4.sql
	modified :         migrations/20240627525836_publish_collab_5.sql
	modified :         migrations/20240629035230_publish_collab_6.sql
	modified :         migrations/20240630010030_workspace_member_foreign_key.sql
	modified :         migrations/20240910100000_af_collab_embeddings_indices.sql
```

The last problem I encounter, is after receiving the magic link my user can't create user in af_user table because of row low-level security policies. I suppose it has not the anon or authenticated role only supabase_admin or none (not sure on this one if role supposed to be the column role in auth.users table or something else). (see https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/838#issuecomment-2391193920)

```
select * from pg_policies;
 schemaname |      tablename      |         policyname         | permissive |        roles         |  cmd   | qual | with_check 
------------+---------------------+----------------------------+------------+----------------------+--------+------+------------
 auth       | af_user             | af_user_select_policy      | PERMISSIVE | {anon,authenticated} | SELECT | true | 
 auth       | af_user             | af_user_update_policy      | PERMISSIVE | {public}             | UPDATE | true | true
 auth       | af_user             | af_user_insert_policy      | PERMISSIVE | {anon,authenticated} | INSERT |      | true
 auth       | af_workspace_member | af_workspace_member_policy | PERMISSIVE | {anon,authenticated} | ALL    | true | 
 auth       | af_workspace        | af_workspace_policy        | PERMISSIVE | {anon,authenticated} | ALL    | true | 
 auth       | af_collab           | af_collab_policy           | PERMISSIVE | {anon,authenticated} | ALL    | true | 
```

Postgres error log
```
ERROR:  new row violates row-level security policy for table "af
_user"
2024-10-04 22:33:38.682 UTC [8711] user@database STATEMENT:  
            WITH ins_user AS (
                INSERT INTO af_user (uid, uuid, email, name)
                VALUES ($1, $2, $3, $4)
                RETURNING uid
            ),
            owner_role AS (
                SELECT id FROM af_roles WHERE name = 'Owner'
            ),
            ins_workspace AS (
                INSERT INTO af_workspace (owner_uid)
                SELECT uid FROM ins_user
                RETURNING workspace_id, owner_uid
            ),
            ins_collab_member AS (
                INSERT INTO af_collab_member (uid, oid, permission_id)
                SELECT ins_workspace.owner_uid,
                       ins_workspace.workspace_id::TEXT,
                       (SELECT permission_id FROM af_role_permissions WHERE role_id = owner_role.id)
                FROM ins_workspace, owner_role
            )
            SELECT workspace_id FROM ins_workspace;
```

Thanks for your work, let me know if I can help you in any way.

**Comment by khorshuheng** [comment]
Let me look into the row security issue, I might have been too hasty in concluding that anon and authenticated roles can be deprecated. 

In any case, the requirement of running AppFlowy cloud using postgres superuser is certainly not ideal, though patching the schema in a way that doesn't break existing installation is going to be tricky. We don't use ORM, but we do use the sqlx library to handle our migration.

**Comment by khorshuheng** [comment]
@Schoumi I was able to reproduced your issue on my local deployment. Debugging now.

**Comment by khorshuheng** [comment]
Row level security will need to be removed from these migrations so that appflowy can use non-superuser:
- migrations/20230312043023_user_patched_20241006.sql
- migrations/20230906101222_workspace_patched_20241006.sql
- migrations/20230906102651_collab_patched_20241006.sql

I don't think we need row level security, though more testing is need. Although changing these migration files will certainly break existing installation due to checksum mismatch. Finding ways to circumvent this.

**Comment by khorshuheng** [comment]
@Schoumi May i also know what changes have you made to the tables? I was able to get the services running with non-postgres user, different database name, and also separate user for gotrue service, but i didn't modify as many migrations.

**Comment by Schoumi** [comment]
I may have been a bit violent with the modifications since i have made them with sed :)
Since they exist 37 migrations scripts i didn't want to debug one by one.

```diff
index 07bb72b7..b6264840 100644
--- a/migrations/20230312043023_user.sql
+++ b/migrations/20230312043023_user.sql
@@ -33,14 +33,14 @@ UPDATE ON af_user FOR EACH ROW EXECUTE FUNCTION prevent_reset_encryption_sign_fu
 -- Enable RLS on the af_user table
 -- Policy for INSERT
 ALTER TABLE af_user ENABLE ROW LEVEL SECURITY;
-CREATE POLICY af_user_insert_policy ON public.af_user FOR
+CREATE POLICY af_user_insert_policy ON auth.af_user FOR
 INSERT TO anon,
     authenticated WITH CHECK (true);
 -- Policy for UPDATE
-CREATE POLICY af_user_update_policy ON public.af_user FOR
+CREATE POLICY af_user_update_policy ON auth.af_user FOR
 UPDATE USING (true) WITH CHECK (true);
 -- Policy for SELECT
-CREATE POLICY af_user_select_policy ON public.af_user FOR
+CREATE POLICY af_user_select_policy ON auth.af_user FOR
 SELECT TO anon,
     authenticated USING (true);
 ALTER TABLE af_user FORCE ROW LEVEL SECURITY;
```
```diff
index c89c669a..25364f36 100644
--- a/migrations/20231130140000_user_delete_trigger.sql
+++ b/migrations/20231130140000_user_delete_trigger.sql
@@ -1,28 +1,28 @@
-GRANT SELECT, INSERT, UPDATE, DELETE ON public.af_user TO supabase_auth_admin;
+GRANT SELECT, INSERT, UPDATE, DELETE ON auth.af_user TO myuser;
 
--- Trigger Function to delete a user from the pulic.af_user table
+-- Trigger Function to delete a user from the auth.af_user table
 -- when a user is deleted from auth.users table (with matching uuid) field
-CREATE OR REPLACE FUNCTION public.delete_user()
+CREATE OR REPLACE FUNCTION auth.delete_user()
 RETURNS TRIGGER AS $$
 BEGIN
-    DELETE FROM public.af_user WHERE uuid = OLD.id;
+    DELETE FROM auth.af_user WHERE uuid = OLD.id;
     RETURN OLD;
 END;
 $$ LANGUAGE plpgsql;
 
 CREATE TRIGGER delete_user_trigger
 AFTER DELETE ON auth.users
-FOR EACH ROW EXECUTE FUNCTION public.delete_user();
+FOR EACH ROW EXECUTE FUNCTION auth.delete_user();
 
--- Trigger Function to update the 'deleted_at' field in the pulic.af_user table
+-- Trigger Function to update the 'deleted_at' field in the auth.af_user table
 -- (Soft Delete)
-CREATE OR REPLACE FUNCTION public.update_af_user_deleted_at()
+CREATE OR REPLACE FUNCTION auth.update_af_user_deleted_at()
 RETURNS TRIGGER AS $$
 BEGIN
     -- Check if 'deleted_at' field is modified
     IF OLD.deleted_at IS DISTINCT FROM NEW.deleted_at THEN
-        -- Update 'deleted_at' in public.af_user
-        UPDATE public.af_user
+        -- Update 'deleted_at' in auth.af_user
+        UPDATE auth.af_user
         SET deleted_at = NEW.deleted_at
         WHERE uuid = NEW.id;
     END IF;
@@ -32,4 +32,4 @@ $$ LANGUAGE plpgsql;
 
 CREATE TRIGGER update_af_user_deleted_at_trigger
 AFTER UPDATE OF deleted_at ON auth.users
-FOR EACH ROW EXECUTE FUNCTION public.update_af_user_deleted_at();
+FOR EACH ROW EXECUTE FUNCTION auth.update_af_user_deleted_at();
```
```diff
index 12be9e89..adaa38b3 100644
--- a/migrations/20231130150000_user_id_foreign_key.sql
+++ b/migrations/20231130150000_user_id_foreign_key.sql
@@ -1,20 +1,20 @@
 -- Revert the last migration
-REVOKE SELECT, INSERT, UPDATE, DELETE ON public.af_user FROM supabase_auth_admin;
+--REVOKE SELECT, INSERT, UPDATE, DELETE ON auth.af_user FROM myuser;
 DROP TRIGGER delete_user_trigger ON auth.users;
 DROP TRIGGER update_af_user_deleted_at_trigger ON auth.users;
-DROP FUNCTION public.delete_user();
-DROP FUNCTION public.update_af_user_deleted_at();
+DROP FUNCTION auth.delete_user();
+DROP FUNCTION auth.update_af_user_deleted_at();
 
--- Delete all users from public.af_user table that are not in auth.users table
-DELETE FROM public.af_user
+-- Delete all users from auth.af_user table that are not in auth.users table
+DELETE FROM auth.af_user
 WHERE NOT EXISTS (
     SELECT 1
     FROM auth.users
     WHERE af_user.uuid = users.id
 );
 
--- Add foreign key constraint to public.af_user table
-ALTER TABLE public.af_user
+-- Add foreign key constraint to auth.af_user table
+ALTER TABLE auth.af_user
 ADD CONSTRAINT af_user_email_foreign_key
 FOREIGN KEY (uuid)
 REFERENCES auth.users(id)
```
```diff
index 3ae74b50..bac9a012 100644
--- a/migrations/20240123140707_workspace_owner_trigger.sql
+++ b/migrations/20240123140707_workspace_owner_trigger.sql
@@ -2,11 +2,11 @@ CREATE OR REPLACE FUNCTION af_workspace_insert_trigger()
 RETURNS TRIGGER AS $$
 BEGIN
     -- Insert a record into af_workspace_member
-    INSERT INTO public.af_workspace_member (
+    INSERT INTO auth.af_workspace_member (
 	uid, role_id,
 	workspace_id, created_at, updated_at)
     VALUES (
-	NEW.owner_uid, (SELECT id FROM public.af_roles WHERE name = 'Owner'),
+	NEW.owner_uid, (SELECT id FROM auth.af_roles WHERE name = 'Owner'),
 	NEW.workspace_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
 
     -- Return the new record to complete the insert operation
@@ -15,6 +15,6 @@ END;
 $$ LANGUAGE plpgsql;
 
 CREATE TRIGGER af_workspace_after_insert
-AFTER INSERT ON public.af_workspace
+AFTER INSERT ON auth.af_workspace
 FOR EACH ROW
 EXECUTE FUNCTION af_workspace_insert_trigger();
```
```diff
index 998cee13..6de36edf 100644
--- a/migrations/20240304173938_workspace_invitation.sql
+++ b/migrations/20240304173938_workspace_invitation.sql
@@ -45,8 +45,8 @@ BEGIN
       NEW.invitee,
       NEW.workspace_id,
       (SELECT permission_id
-       FROM public.af_role_permissions
-       WHERE public.af_role_permissions.role_id = NEW.role_id)
+       FROM auth.af_role_permissions
+       WHERE auth.af_role_permissions.role_id = NEW.role_id)
     )
     ON CONFLICT (uid, oid)
     DO UPDATE
```
```diff
index 8c301d34..3949185c 100644
--- a/migrations/20240306110000_workspace_invitation_2.sql
+++ b/migrations/20240306110000_workspace_invitation_2.sql
@@ -20,8 +20,8 @@ BEGIN
       (SELECT uid FROM af_user WHERE email = NEW.invitee_email),
       NEW.workspace_id,
       (SELECT permission_id
-       FROM public.af_role_permissions
-       WHERE public.af_role_permissions.role_id = NEW.role_id)
+       FROM auth.af_role_permissions
+       WHERE auth.af_role_permissions.role_id = NEW.role_id)
     )
     ON CONFLICT (uid, oid)
     DO UPDATE
```
```diff
index f2a5b62a..514b49d3 100644
--- a/migrations/20240626184736_publish_collab_4.sql
+++ b/migrations/20240626184736_publish_collab_4.sql
@@ -1,6 +1,6 @@
 -- Add a unique constraint on publish_name
-ALTER TABLE public.af_published_collab
+ALTER TABLE auth.af_published_collab
 ADD CONSTRAINT unique_publish_name UNIQUE (publish_name);
 
 -- Add an index on publish_name
-CREATE INDEX idx_publish_name ON public.af_published_collab (publish_name);
+CREATE INDEX idx_publish_name ON auth.af_published_collab (publish_name);
```
```diff
index 605ab2f3..48f49694 100644
--- a/migrations/20240627525836_publish_collab_5.sql
+++ b/migrations/20240627525836_publish_collab_5.sql
@@ -1,7 +1,7 @@
 -- Drop the existing unique constraint on publish_name
-ALTER TABLE public.af_published_collab
+ALTER TABLE auth.af_published_collab
 DROP CONSTRAINT unique_publish_name;
 
 -- Add a new unique constraint for the combination of publish_name and workspace_id
-ALTER TABLE public.af_published_collab
+ALTER TABLE auth.af_published_collab
 ADD CONSTRAINT unique_workspace_id_publish_name UNIQUE (workspace_id, publish_name);
```
```diff
index 7a6ae459..b32e4ef8 100644
--- a/migrations/20240629035230_publish_collab_6.sql
+++ b/migrations/20240629035230_publish_collab_6.sql
@@ -1,9 +1,9 @@
 -- Update existing null values to ensure no nulls are present before adding NOT NULL constraint
-UPDATE public.af_workspace
+UPDATE auth.af_workspace
 SET publish_namespace = uuid_generate_v4()::text
 WHERE publish_namespace IS NULL;
 
 -- Alter the column to set NOT NULL constraint and a default value
-ALTER TABLE public.af_workspace
+ALTER TABLE auth.af_workspace
 ALTER COLUMN publish_namespace SET NOT NULL,
 ALTER COLUMN publish_namespace SET DEFAULT uuid_generate_v4()::text;
```
```diff
index 9ff48923..f4211813 100644
--- a/migrations/20240630010030_workspace_member_foreign_key.sql
+++ b/migrations/20240630010030_workspace_member_foreign_key.sql
@@ -1,3 +1,3 @@
-ALTER TABLE public.af_workspace_member
+ALTER TABLE auth.af_workspace_member
 ADD CONSTRAINT af_workspace_member_uid_fkey
 FOREIGN KEY (uid) REFERENCES af_user(uid) ON DELETE CASCADE;
```
```diff
index a96761d4..4c479473 100644
--- a/migrations/20240910100000_af_collab_embeddings_indices.sql
+++ b/migrations/20240910100000_af_collab_embeddings_indices.sql
@@ -1,6 +1,6 @@
 DO $$
 BEGIN
-    CREATE INDEX IF NOT EXISTS af_collab_embeddings_oid_idx ON public.af_collab_embeddings (oid);
+    CREATE INDEX IF NOT EXISTS af_collab_embeddings_oid_idx ON auth.af_collab_embeddings (oid);
 EXCEPTION WHEN others THEN
     RAISE NOTICE 'could not create index on af_collab_embeddings(oid), ignoring this migration';
 END $$;
```

And yes i confirm the checksum fail if you modify a migration script that has been already run. I did try that when i remove the line that revoke access to my user.

Remove low level security will not be the problem, you can do that in a migration script. The major problem is migrate from postgres/supabase_auth_admin to the user/pass/db set in environment variable. I've no knowledge of postgres but maybe is it possible to rename db/user and migrate data from one db to another as superadmin? With that, you'll have to use default values to run all migrations and after the new one is applied you'll use new database/user/password for that
