### ISSUE TITLE
[Bug] Do not show credentials in the logs !

### ISSUE THREAD

**Issue by chevdor** [AppFlowy-IO/AppFlowy-Cloud#907]
**Describe the bug**
No credential should ever be shown in the logs...
See https://github.com/AppFlowy-IO/AppFlowy/issues/6583 for an example.

**To Reproduce**
1. look at the startup logs

**Expected behavior**
No credential is **ever** shown in the logs

**Screenshots**
<img width="1568" alt="image" src="https://github.com/user-attachments/assets/70f42021-8748-4df9-b6b6-34de4571bb64">

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by wolfspyre** [comment]
yeah. this **MUST** be fixed. 
additionally; I'd encourage tests be put in place to inspect the emitted logs for sensitive data... 

(this stuff has a nasty habit of getting re-enabled from dev pr's.... having a test to make sure that no verboselog happens to shout your `hunter2` to the wide-wide-world-of-logs.... will make it a lot easier to ensure it doesnt happen again.
