### ISSUE TITLE
[Bug] 20240729123726_add_mfa_phone_config fails unless enum is manually created

### ISSUE THREAD

**Issue by chevdor** [AppFlowy-IO/AppFlowy-Cloud#909]
**Describe the bug**
Starting gotrue on a fresh DB almost works :)
The migrations work until `20240729123726_add_mfa_phone_config`.
It fails with:
```
{"level":"fatal","msg":"running db migrations: error executing migrations/20240729123726_add_mfa_phone_config.up.sql, sql: do $$ begin\n    alter type auth.factor_type add value 'phone';\nexception\n    when duplicate_object then null;\nend $$;\n\n\nalter table auth.mfa_factors add column if not exists phone text unique default null;\nalter table auth.mfa_challenges add column if not exists otp_code text null;\n\n\ncreate unique index if not exists unique_verified_phone_factor on auth.mfa_factors (user_id, phone);\n: ERROR: type \"auth.factor_type\" does not exist (SQLSTATE 42704)","time":"2024-10-19T20:08:47Z"}
```

I am not sure if the enum should be created with some content but at least the following allowed the migrations to complete and gotrue to start:
```
CREATE TYPE auth.factor_type AS ENUM ();
```

**To Reproduce**
1. start with a fresh db
2. apply the "before" migrations
3. start gotrue

**Expected behavior**
The migrations succeed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
k8s

**Additional context**
n/a

**Comment by khorshuheng** [comment]
What is the gotrue image tag which you used when you faced this issue?

**Comment by chevdor** [comment]
` appflowyinc/gotrue`

The version does not see to be logged but the container [appears](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/docker/gotrue.Dockerfile#L3) to be based on  v`2.159.1`.

I also tried building a updated version pushed to my local registry and based on `2.163.0`
