### ISSUE TITLE
[FR] simplify environment settings

### ISSUE THREAD

**Issue by ThanatosDi** [AppFlowy-IO/AppFlowy-Cloud#917]
Are the domain of API_EXTERNAL_URL and the domain of GOTRUE OAuth2 necessarily the same?
maybe can simplify the oauth redirect url setting.

now I try to detaching the postgres settings. like host, port, username etc...

**Comment by khorshuheng** [comment]
Under normal circumstance, yes. It should be alright to use the same domain.

**Comment by wolfspyre** [comment]
After teasing this apart a bit, I don't think that an environment file is necessarily the **wrong** way to go here; with some love.

Something that I do think is needed here is a clear distillation of what should be set where and how. 

This is one of the challenges that arise with multiple layers of abstraction points that has been faced in many config management tools... 

when there's 5 different ways to adjust the sensitivity of a thing... and each of them work **MOSTLY** the same... it's initially not that big a deal to be somewhat cavalier about where things are declared and consumed.... 

But as you can see here... this quickly becomes akin to the scene in `the wizard's apprentice` ...

it's a bit unwieldy...

I think adopting a single env file that's added to each node declaration could go a long way towards reducing the confusion.

additionally, I think having the services emit a report of their config status somehow before starting may go a long way towards pointing people in the right direction when things are wonky.

(or maybe it does that already and I'm just blind)
