### ISSUE TITLE
[Bug] supabase_auth_admin user not found

### ISSUE THREAD

**Issue by ThanatosDi** [AppFlowy-IO/AppFlowy-Cloud#934]
**Describe the bug**

PR #918 can custom setting supabase username, but miss check migrations, will let that init failed.
some migrations need origin username setting "supabase_auth_admin".

**Fix**

1. set supabase username hard code, still use "supabase_auth_admin", and custom username is not allowed.
2. change some migrations from .sql to shell script, that can get value from env variable

Any suggestions for these two solutions?

@speed2exe , @khorshuheng

**Comment by khorshuheng** [comment]
Option 2 would not be possible, because the migration SQL files are used by the sqlx library, and as far as I know, does not support shell script nor variable substitution.

I would suggest going with option 1 for now. Meanwhile, I will explore other options.
