### ISSUE TITLE
[Bug] PC and mobile Spaces (inside WorkSpaces) don't sync

### ISSUE THREAD

**Issue by casainho** [AppFlowy-IO/AppFlowy-Cloud#952]
**Describe the bug**
I am using selfhost. WorkSpaces do sync, like create, delete, change name, icon, etc. But the Spaces inside, seems they are totally different from PC and mobile.

I checked that using AppFlowy.com instead of selfhost, works as expected.
I checked on selfhost the user as also the size of each WorkSpace, that increases / decreases as expected, but like if they are duplicated for Mobile / PC.

![Screenshot from 2024-10-30 09-22-12](https://github.com/user-attachments/assets/26b66e17-a051-43c4-85a1-c7befe6acb91)

**To Reproduce**
1. Install [0.6.55](https://github.com/AppFlowy-IO/AppFlowy-Cloud/releases/tag/0.6.55)
2. Configure PC and Mobile apps to the same user of selfhosting
3. Add or remove pages on Spaces and see if they are the same or not on PC and Mobile

**Expected behavior**
Spaces contents should be equal both on PC and Mobile apps.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser: Firefox

**Comment by khorshuheng** [comment]
Can you check the nginx access log and check if the websocket endpoints (request with /ws/v1 prefix) are working as expected?

**Comment by casainho** [comment]
@khorshuheng since you did mention websocket nginx, then I went and enable websocket on nginx reverse proxy configuration and now it works!!! Many thanks to you 👍👍❤️

![Screenshot_20241030_154753_Firefox](https://github.com/user-attachments/assets/8417b39d-3217-4ad0-9003-8676f22221f7)

**Comment by casainho** [comment]
Solved. Thanks to @khorshuheng.
