### ISSUE TITLE
[Bug] AI chat doesn't seem to sync? "A unicorn ate our response"

### ISSUE THREAD

**Issue by bdruth** [AppFlowy-IO/AppFlowy-Cloud#960]
**Describe the bug**
When pulling up an AI Chat from a device that isn't the one that initiated it, the chat doesn't appear to sync and then on the device that initiated it, an error is displayed.

**To Reproduce**
1. Create an AI Chat
2. Ask a question, wait for the response
3. Access the AI Chat from a sync'd device
4. The 2nd device only shows the question asked
5. The 1st device shows an error (the response disappears)

**Expected behavior**
AI Chat response is visible on both devices

**Screenshots**
Primary Device
<img width="778" alt="image" src="https://github.com/user-attachments/assets/32ec14db-5282-446a-90aa-9a8931d84ef6">

Second Device
![image](https://github.com/user-attachments/assets/888c1585-28e4-4283-864e-2f938f0ee347)

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.1
 - Browser n/a
 - Version 0.7.2

**Additional context**
 - Environment: self-hosted

Sync works otherwise (websocket support is enabled & working)

**Comment by appflowy** [comment]
@bdruth The message A unicorn ate our response indicates that the AI service is temporarily unavailable. As a result, the response will not be synced to other devices.

**Comment by appflowy** [comment]
I will close this PR. Feel free to reopen
